<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <SonarQubeTestProject>true</SonarQubeTestProject>
    <NoWarn>NU1608</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="8.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.2.1" PrivateAssets="all" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\VirtoCommerce.UCP.Core\VirtoCommerce.UCP.Core.csproj" />
    <ProjectReference Include="..\..\src\VirtoCommerce.UCP.Data\VirtoCommerce.UCP.Data.csproj" />
    <ProjectReference Include="..\..\src\VirtoCommerce.UCP.ExperienceApi\VirtoCommerce.UCP.ExperienceApi.csproj" />
    <ProjectReference Include="..\..\src\VirtoCommerce.UCP.Web\VirtoCommerce.UCP.Web.csproj" />
  </ItemGroup>
</Project>
